#!/bin/bash
value=$(gsettings get org.gnome.desktop.notifications show-banners)
echo "$value"
if [[ $value == 'true' ]]
then
  echo here
  gsettings set org.gnome.desktop.notifications show-banners false
else
  echo no
  gsettings set org.gnome.desktop.notifications show-banners true
fi